// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4DP_xf5m5cKUrX2e0fXZdh6qo681_FgU',
    appId: '1:409525565675:web:24db1c895d3603969ea6ae',
    messagingSenderId: '409525565675',
    projectId: 'leaplottoza',
    authDomain: 'leaplottoza.firebaseapp.com',
    storageBucket: 'leaplottoza.appspot.com',
    measurementId: 'G-WXRD7DJVJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0m6WJhplsG_t1Qje4nr5q2iksb8Q025U',
    appId: '1:409525565675:android:64a9ce4e6fdc69e49ea6ae',
    messagingSenderId: '409525565675',
    projectId: 'leaplottoza',
    storageBucket: 'leaplottoza.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn1xFhQzn2b3_O2jYeBW9LHSdgklNRBDQ',
    appId: '1:409525565675:ios:1c8170e502edff1a9ea6ae',
    messagingSenderId: '409525565675',
    projectId: 'leaplottoza',
    storageBucket: 'leaplottoza.appspot.com',
    iosBundleId: 'com.example.lottodash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn1xFhQzn2b3_O2jYeBW9LHSdgklNRBDQ',
    appId: '1:409525565675:ios:1c8170e502edff1a9ea6ae',
    messagingSenderId: '409525565675',
    projectId: 'leaplottoza',
    storageBucket: 'leaplottoza.appspot.com',
    iosBundleId: 'com.example.lottodash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4DP_xf5m5cKUrX2e0fXZdh6qo681_FgU',
    appId: '1:409525565675:web:f9cfa61807311e1a9ea6ae',
    messagingSenderId: '409525565675',
    projectId: 'leaplottoza',
    authDomain: 'leaplottoza.firebaseapp.com',
    storageBucket: 'leaplottoza.appspot.com',
    measurementId: 'G-JQ2P9E1KTK',
  );

}